### PR TITLE
check folder /opt/mesosphere/ is empty

### PR DESCRIPTION
**Pull request by minitux**
dcos install only need an empty directory to check master or agent is not already install

### CODE REVIEW

**Comment by deric** [comment]
@minitux Thanks!

Could you add there double quotes? In case that `/opt/mesosphere` is not empty it would return multiple arguments. 
```
test -z `ls -A /opt/mesosphere`
-bash: test: too many arguments
```
it should be better to use:
```
test -z "`ls -A /opt/mesosphere`"
```

**Comment by minitux** [comment]
thks nice catch !

**Comment by minitux** [comment]
Thanks, 

I will need a new tag release to get it on my puppet server.

Will you do it ?

**Comment by deric** [comment]
Sure, it's tagged as [`v0.4.3`](https://github.com/deric/puppet-dcos/releases/tag/v0.4.3) and available at Puppet Forge.

**Pull request merged**
